/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/account/passkeys": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["register"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/passkeys/options": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["registration_options"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/passkeys/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete_passkey"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Changes the own password and ends all other own sessions. */
		post: operations["change_password"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/recovery-codes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Replaces the recovery codes. The old codes stop working. */
		post: operations["new_recovery_codes"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/second-factors": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_factors"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/sessions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_sessions"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/sessions/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete_session"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/totp": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Starts TOTP setup with a new secret. The secret is active only after confirmation. */
		post: operations["start_totp"];
		delete: operations["delete_totp"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/totp/confirm": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["confirm_totp"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/admins": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_admins"];
		put?: never;
		post: operations["create_admin"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/admins/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete_admin"];
		options?: never;
		head?: never;
		/** Disables or enables an admin. Disabling ends all sessions of that admin. */
		patch: operations["update_admin"];
		trace?: never;
	};
	"/admins/{id}/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sets a new password and ends the sessions of that admin (for the own account: all other sessions). */
		post: operations["reset_password"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/admins/{id}/second-factors/reset": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Removes all second factors of an admin and ends the sessions of that admin. */
		post: operations["reset_factors"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/aliases": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_aliases"];
		put?: never;
		post: operations["create_alias"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/aliases/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["update_alias"];
		post?: never;
		delete: operations["delete_alias"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api-keys": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_keys"];
		put?: never;
		post: operations["create_key"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api-keys/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["update_key"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api-keys/{id}/revoke": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Revokes a key. It stops working at once. Revoked keys stay listed for the usage history. */
		post: operations["revoke_key"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["logout"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["me"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/passkey": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["passkey_login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/passkey/options": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["passkey_login_options"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** The second factors for the pending login. */
		get: operations["pending_methods"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor/passkey": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["verify_second_factor"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor/passkey/options": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["second_factor_options"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor/recovery-code": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["verify_recovery_code"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor/totp": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["verify_totp"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/accounts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_accounts"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/accounts/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Removes the account. If it was the primary account, the next one in the order becomes primary. */
		delete: operations["delete_account"];
		options?: never;
		head?: never;
		patch: operations["update_account"];
		trace?: never;
	};
	"/chatgpt/accounts/{id}/models/sync": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["sync_models"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/accounts/{id}/primary": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["make_primary"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/accounts/{id}/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["refresh_now"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/accounts/{id}/usage/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Polls the usage of the account now. This works also when the usage poll is off. */
		post: operations["refresh_usage"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/failover-order": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["set_failover_order"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/link/device": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["start_device_link"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/link/pkce": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["start_pkce_link"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/link/{flow}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["link_status"];
		put?: never;
		post?: never;
		delete: operations["cancel_link"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/link/{flow}/callback": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["complete_pkce_link"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/connections": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_connections"];
		put?: never;
		post: operations["create_connection"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/connections/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Deletes the connection and its models. Aliases that point to it stop working. */
		delete: operations["delete_connection"];
		options?: never;
		head?: never;
		patch: operations["update_connection"];
		trace?: never;
	};
	"/connections/{id}/sync": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Loads the model list again. New models start disabled. */
		post: operations["sync_connection"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/models": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_models"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/models/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["update_model"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pricing/models": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** The prices that apply to each enabled model now. */
		get: operations["model_prices"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pricing/overrides": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_overrides"];
		put?: never;
		/** New costs use the override at once; stored rows change only with a recompute. */
		post: operations["create_override"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pricing/overrides/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Saves the prices as a new version. Rows with the old version keep it until a recompute. */
		put: operations["update_override"];
		post?: never;
		/** The override stops applying; its versions stay for the rows that use them. */
		delete: operations["delete_override"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pricing/recompute": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["recompute_status"];
		put?: never;
		/** Recalculates the cost of the rows in the time range with the current prices. */
		post: operations["start_recompute"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pricing/sources": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_sources"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/pricing/sync": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Loads all price lists now. Returns when the sync is done. */
		post: operations["sync_now"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/settings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_settings"];
		put: operations["put_settings"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/settings/cron-preview": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * The next 3 run times of a cron plan. The server computes them, so the dashboard shows what
		 *     the scheduler does.
		 */
		post: operations["cron_preview"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/setup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["setup_status"];
		put?: never;
		/** Creates the first admin with the setup token and logs in. */
		post: operations["setup"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/stats": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * StatsTotals, a series per group and bucket, and the cost per category. Buckets have local
		 *     borders in the time zone of the request.
		 */
		post: operations["stats"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AccountUpdate: {
			/** @description Take part in failover. */
			failover_enabled: boolean;
			label?: string | null;
			/** @description Needed when `refresh_mode` is `custom`. */
			refresh_cron?: string | null;
			/** @description `inherit`, `custom` or `disabled`. */
			refresh_mode: string;
		};
		AccountView: {
			/** Format: int64 */
			access_expires_at?: number | null;
			/** Format: int64 */
			created_at: number;
			credits_balance?: string | null;
			credits_unlimited?: boolean | null;
			email?: string | null;
			failover_enabled: boolean;
			/** Format: int64 */
			failover_order: number;
			/** @description Credits of the account, from the last usage poll. */
			has_credits?: boolean | null;
			/** Format: int64 */
			id: number;
			is_primary: boolean;
			label?: string | null;
			/** Format: int64 */
			last_refresh_at: number;
			last_refresh_error?: string | null;
			/** Format: int64 */
			last_refresh_failed_at?: number | null;
			/**
			 * Format: int64
			 * @description A usage-limit error blocks the account until this time.
			 */
			limited_until?: number | null;
			/** Format: int64 */
			models: number;
			models_last_error?: string | null;
			/**
			 * Format: int64
			 * @description Time of the last good model list sync.
			 */
			models_last_sync_at?: number | null;
			/**
			 * Format: int64
			 * @description Next scheduled refresh, computed from the plan.
			 */
			next_refresh_at?: number | null;
			plan_type?: string | null;
			/** Format: int64 */
			primary_reset_at?: number | null;
			/**
			 * Format: double
			 * @description Usage limits from the last backend answer (usually a 5-hour and a weekly window).
			 */
			primary_used_percent?: number | null;
			/** Format: int64 */
			primary_window_minutes?: number | null;
			/** Format: int64 */
			quota_updated_at?: number | null;
			refresh_cron?: string | null;
			/** @description `inherit`, `custom` or `disabled`. */
			refresh_mode: string;
			/** Format: int64 */
			secondary_reset_at?: number | null;
			/** Format: double */
			secondary_used_percent?: number | null;
			/** Format: int64 */
			secondary_window_minutes?: number | null;
			/** @description `active` or `needs_relogin`. */
			status: string;
		};
		AdminView: {
			/** Format: int64 */
			created_at: number;
			disabled: boolean;
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			last_login_at?: number | null;
			/** @description True when the admin has TOTP or a passkey. */
			second_factor: boolean;
			username: string;
		};
		AliasSettings: {
			default_effort?: string | null;
			default_fast?: boolean;
			default_summary?: string | null;
			description?: string | null;
			name: string;
			target: string;
		};
		AliasView: {
			/** Format: int64 */
			created_at: number;
			default_effort?: string | null;
			default_fast: boolean;
			/** @description `auto`, `concise` or `detailed`. */
			default_summary?: string | null;
			description?: string | null;
			/** Format: int64 */
			id: number;
			name: string;
			/** @description `chatgpt/<model>` or `<connection slug>/<model>`. */
			target: string;
			/** @description False when the target model is missing or disabled: the alias does not work then. */
			target_enabled: boolean;
		};
		ApiKeyView: {
			allowlist: string[];
			/**
			 * Format: int64
			 * @description Parallel requests. `None`: the default of 8.
			 */
			concurrency_limit?: number | null;
			/** Format: int64 */
			created_at: number;
			created_by?: string | null;
			/** Format: int64 */
			expires_at?: number | null;
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			last_used_at?: number | null;
			name: string;
			prefix: string;
			/** Format: int64 */
			revoked_at?: number | null;
			/** Format: int64 */
			rpm_limit?: number | null;
			/** Format: int64 */
			tpm_limit?: number | null;
		};
		AssertionRequest: {
			ceremony: string;
			credential: unknown;
		};
		/**
		 * @description What a model can do. Every key is optional; a missing key means "unknown". The keys are
		 *     described in `connections::models`.
		 */
		Capabilities: {
			chat_tools?: boolean | null;
			/** Format: int64 */
			context_window?: number | null;
			default_effort?: string | null;
			efforts?: string[] | null;
			endpoints?: string[] | null;
			fast?: boolean | null;
			forced_tools_with_thinking?: boolean | null;
			input?: string[] | null;
			/** Format: int64 */
			max_output?: number | null;
			mode?: string | null;
			thinking?: components["schemas"]["Thinking"] | null;
			thinking_always_on?: boolean | null;
		};
		/** @description The capabilities that an admin can change. */
		CapabilityOverrides: {
			chat_tools?: boolean | null;
			/** Format: int64 */
			context_window?: number | null;
			efforts?: string[] | null;
			endpoints?: string[] | null;
			fast?: boolean | null;
			forced_tools_with_thinking?: boolean | null;
			input?: string[] | null;
			/** Format: int64 */
			max_output?: number | null;
			thinking?: components["schemas"]["Thinking"] | null;
			thinking_always_on?: boolean | null;
		};
		ChangePassword: {
			current_password: string;
			new_password: string;
		};
		CodeRequest: {
			code: string;
		};
		ConnectionUpdate: {
			/** @description A new key. Empty or missing: keep the key. */
			api_key?: string | null;
			base_url?: string | null;
			display_name: string;
		};
		ConnectionView: {
			/** @description The last 4 characters of the API key. */
			api_key_last4: string;
			base_url?: string | null;
			/** Format: int64 */
			created_at: number;
			display_name: string;
			/** Format: int64 */
			enabled_models: number;
			/** Format: int64 */
			id: number;
			/** @description `openai`, `anthropic` or `openrouter`. */
			kind: string;
			/** @description The error of the last model list request. */
			last_error?: string | null;
			/** Format: int64 */
			last_sync_at?: number | null;
			/** Format: int64 */
			models: number;
			/** @description The model prefix, for example `anthropic-main` in `anthropic-main/claude-opus-5-5`. */
			slug: string;
		};
		/**
		 * @description Prices for long requests: they apply when the input of one request is above `above` tokens.
		 *     An empty field keeps the price below the limit.
		 */
		ContextTier: {
			/** Format: int64 */
			above: number;
			flex?: components["schemas"]["TokenPrices"] | null;
			priority?: components["schemas"]["TokenPrices"] | null;
			standard: components["schemas"]["TokenPrices"];
		};
		CreateAdmin: {
			password: string;
			username: string;
		};
		CreatedKey: {
			api_key: components["schemas"]["ApiKeyView"];
			/** @description The full key. It is shown only once. */
			key: string;
		};
		CronPreview: {
			/** @description The next 3 runs, unix seconds. */
			next_runs: number[];
		};
		CronPreviewRequest: {
			cron: string;
			/** @description Default: the instance time zone. */
			time_zone?: string | null;
		};
		DeviceLink: {
			flow: string;
			user_code: string;
			verification_url: string;
		};
		ErrorBody: {
			error: components["schemas"]["ErrorDetail"];
		};
		ErrorDetail: {
			code: string;
			message: string;
		};
		FactorAdded: {
			/** @description New recovery codes, only when this is the first second factor. Show them once. */
			recovery_codes?: string[] | null;
		};
		Factors: {
			passkeys: components["schemas"]["PasskeyView"][];
			/** Format: int64 */
			recovery_codes_left: number;
			totp: boolean;
		};
		Failover: {
			enabled: boolean;
			/**
			 * Format: int32
			 * @description Switch to the next account when its 5-hour or weekly usage reaches this percentage.
			 */
			threshold_percent: number;
		};
		FailoverOrder: {
			/** @description All account ids in the new order. */
			account_ids: number[];
		};
		/** @description The price of one generated image. */
		ImagePrice: {
			/** @description Empty: all qualities. */
			quality?: string | null;
			/** @description For example `1024x1024`. */
			size: string;
			/** Format: double */
			usd: number;
		};
		/** @description Settings of a key. The same body is used to create and to change a key. */
		KeySettings: {
			/** @description Model patterns, for example `chatgpt/*` or `anthropic-main/claude-opus-5-5`. Empty: all models. */
			allowlist: string[];
			/** Format: int64 */
			concurrency_limit?: number | null;
			/** Format: int64 */
			expires_at?: number | null;
			name: string;
			/** Format: int64 */
			rpm_limit?: number | null;
			/** Format: int64 */
			tpm_limit?: number | null;
		};
		LinkStatus: {
			/** Format: int64 */
			account_id?: number | null;
			message?: string | null;
			/** @description `pending`, `done` or `failed`. */
			status: string;
		};
		LoginRequest: {
			password: string;
			username: string;
		};
		/** @description Either the logged-in admin, or the second factors to use next. */
		LoginResponse: {
			me?: components["schemas"]["Me"] | null;
			second_factor?: components["schemas"]["Methods"] | null;
		};
		Me: {
			/** Format: int64 */
			id: number;
			username: string;
		};
		/** @description The second factors an admin can use. */
		Methods: {
			passkey: boolean;
			recovery_code: boolean;
			totp: boolean;
		};
		ModelPrice: {
			/** @description `chatgpt`, `openai`, `anthropic` or `openrouter`. */
			kind: string;
			/** @description `chatgpt/<model>` or `<connection slug>/<model>`. */
			model: string;
			price?: components["schemas"]["PriceView"] | null;
		};
		ModelUpdate: {
			/** @description Capabilities to change. An empty object removes all changes. */
			capability_overrides: components["schemas"]["CapabilityOverrides"];
			enabled: boolean;
		};
		ModelView: {
			/** @description The synced capabilities. */
			capabilities: components["schemas"]["Capabilities"];
			/** @description Admin changes. They win over the synced capabilities. */
			capability_overrides: components["schemas"]["CapabilityOverrides"];
			display_name?: string | null;
			/** @description The capabilities that the gateway uses. */
			effective: components["schemas"]["Capabilities"];
			enabled: boolean;
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			last_seen_at: number;
			/** @description The name for clients, for example `chatgpt/gpt-5.5` or `or/openai/gpt-5.5`. */
			name: string;
			/** @description `chatgpt`, or the slug of the connection. */
			source: string;
			/** @description `chatgpt`, `openai`, `anthropic` or `openrouter`. */
			source_kind: string;
			upstream_id: string;
		};
		NewConnection: {
			api_key: string;
			/** @description Optional, for example a compatible gateway. Default: the official API. */
			base_url?: string | null;
			display_name: string;
			/** @description `openai`, `anthropic` or `openrouter`. */
			kind: string;
			/** @description Lower-case letters, digits and `-`. It cannot change later. */
			slug: string;
		};
		/** @description WebAuthn options and credentials are passed through as JSON objects. */
		Options: {
			/** @description Id of this ceremony, to send back with the answer. */
			ceremony: string;
			/** @description Options for `navigator.credentials` (`publicKey` member). */
			options: unknown;
		};
		OverridePrices: {
			prices: components["schemas"]["Prices"];
		};
		OverrideSettings: {
			match_key: string;
			prices: components["schemas"]["Prices"];
		};
		OverrideView: {
			/** Format: int64 */
			created_at: number;
			created_by?: string | null;
			/** Format: int64 */
			id: number;
			/** @description `connection/model`, `chatgpt/model` or a model key such as `openai/gpt-5`. */
			match_key: string;
			prices: components["schemas"]["Prices"];
			/** Format: int64 */
			version_id: number;
		};
		PasskeyView: {
			/** Format: int64 */
			created_at: number;
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			last_used_at?: number | null;
			name: string;
		};
		PastedCallback: {
			url: string;
		};
		PkceLink: {
			/** @description Open this address, log in, then paste the address of the page you land on. */
			authorize_url: string;
			flow: string;
		};
		/** @description The last sync of one price list. */
		PriceSource: {
			/**
			 * Format: int64
			 * @description Models with prices in the last good list.
			 */
			entries: number;
			error?: string | null;
			/**
			 * Format: int64
			 * @description Unix seconds of the last attempt.
			 */
			fetched_at?: number | null;
			source: string;
			/** @description `ok` or `error` */
			status: string;
		};
		PriceView: {
			/** @description The override match key or the model key in the list. */
			key: string;
			prices: components["schemas"]["Prices"];
			/** @description `override`, `openrouter`, `litellm` or `models_dev`. */
			source: string;
			/** Format: int64 */
			version: number;
		};
		/** @description All prices of one model from one source. */
		Prices: {
			context_tiers?: components["schemas"]["ContextTier"][];
			fast?: components["schemas"]["TokenPrices"] | null;
			/**
			 * Format: double
			 * @description Anthropic fast mode: the standard prices times this number.
			 */
			fast_multiplier?: number | null;
			flex?: components["schemas"]["TokenPrices"] | null;
			/** @description Anthropic inference geography (`us`) → multiplier for all token prices. */
			geo?: {
				[key: string]: number;
			};
			images?: components["schemas"]["ImagePrice"][];
			/**
			 * @description The source has a price rule that the gateway cannot apply (for example off-peak
			 *     prices), so costs from it are not complete.
			 */
			partial?: boolean;
			/**
			 * Format: double
			 * @description USD per input character (speech).
			 */
			per_character?: number | null;
			/**
			 * Format: double
			 * @description USD per second of input audio (transcription).
			 */
			per_second?: number | null;
			priority?: components["schemas"]["TokenPrices"] | null;
			standard: components["schemas"]["TokenPrices"];
			/**
			 * @description The price changes per request (OpenRouter routers): the cost is unknown, and no other
			 *     list is used for the model.
			 */
			variable?: boolean;
			/**
			 * Format: double
			 * @description USD per call of the `web_search` tool (also Anthropic web search).
			 */
			web_search?: number | null;
			/**
			 * Format: double
			 * @description USD per call of the `web_search_preview` tool.
			 */
			web_search_preview?: number | null;
		};
		RecomputeRequest: {
			/**
			 * Format: int64
			 * @description Unix seconds, inclusive.
			 */
			from: number;
			/** @description Resolved model names (`connection/model`); empty: all models. */
			models?: string[];
			/**
			 * Format: int64
			 * @description Unix seconds, exclusive.
			 */
			to: number;
		};
		RecomputeStatus: {
			/**
			 * Format: int64
			 * @description Rows done and rows in the range.
			 */
			done: number;
			error?: string | null;
			/** Format: int64 */
			finished_at?: number | null;
			/**
			 * Format: int64
			 * @description Unix seconds of the time range.
			 */
			from?: number | null;
			running: boolean;
			/** Format: int64 */
			started_at?: number | null;
			/** Format: int64 */
			to?: number | null;
			/** Format: int64 */
			total: number;
		};
		RecoveryCodes: {
			recovery_codes: string[];
		};
		/** @description A scheduled job (token refresh, price sync). */
		RefreshSchedule: {
			/** @description 5-field cron: minute hour day-of-month month day-of-week. */
			cron: string;
			enabled: boolean;
		};
		RegisterRequest: {
			ceremony: string;
			credential: unknown;
			name: string;
		};
		ResetPassword: {
			password: string;
		};
		SessionView: {
			/** Format: int64 */
			created_at: number;
			/** @description True for the session of this request. */
			current: boolean;
			/** Format: int64 */
			expires_at: number;
			/** Format: int64 */
			id: number;
			ip?: string | null;
			/** Format: int64 */
			last_seen_at: number;
			user_agent?: string | null;
		};
		Settings: {
			failover: components["schemas"]["Failover"];
			/**
			 * @description The price sync from the public price lists.
			 *     Settings saved before the price sync existed have none.
			 */
			price_sync: components["schemas"]["RefreshSchedule"];
			refresh: components["schemas"]["RefreshSchedule"];
			/** @description IANA time zone, for example `Europe/Berlin`. Cron plans use it. */
			time_zone: string;
			/**
			 * @description The regular poll of the ChatGPT account usage.
			 *     Settings saved before the usage poll existed have none.
			 */
			usage_poll: components["schemas"]["UsagePoll"];
		};
		SetupRequest: {
			password: string;
			token: string;
			username: string;
		};
		SetupStatus: {
			/** @description True when no admin exists yet. */
			required: boolean;
		};
		StatsGroup: {
			/** @description The group value: API key id, model name, `chatgpt:<id>`, `connection:<id>` or `all`. */
			key: string;
			label: string;
			/** @description One point per bucket. */
			series: components["schemas"]["StatsPoint"][];
			totals: components["schemas"]["StatsTotals"];
		};
		/** @description One bucket of a group. */
		StatsPoint: {
			/** Format: int64 */
			cost_nano: number;
			/** Format: int64 */
			input_tokens: number;
			/** Format: int64 */
			output_tokens: number;
			/** Format: int64 */
			requests: number;
		};
		StatsRequest: {
			/** @description `hour`, `day`, `week` or `month`; empty: chosen by the length of the range. */
			bucket?: string | null;
			/**
			 * Format: int64
			 * @description Unix seconds, inclusive.
			 */
			from: number;
			/** @description `key`, `model`, `upstream` or `none`. */
			group: string;
			/** @description API key ids; empty: all keys. */
			keys?: number[];
			/** @description Resolved model names; empty: all models. */
			models?: string[];
			/** @description IANA time zone of the buckets, for example `Europe/Berlin`. */
			time_zone: string;
			/**
			 * Format: int64
			 * @description Unix seconds, exclusive.
			 */
			to: number;
			/** @description Upstream group keys (`chatgpt:<account id>`, `connection:<id>`); empty: all. */
			upstreams?: string[];
		};
		StatsResponse: {
			bucket: string;
			/** @description Bucket starts, unix seconds. The first bucket starts at `from`, the last ends at `to`. */
			buckets: number[];
			/** @description Groups by calculated cost, highest first. */
			groups: components["schemas"]["StatsGroup"][];
			/** @description Requests that the gateway refused before routing (keys, limits), per reason. */
			rejected: {
				[key: string]: number;
			};
			totals: components["schemas"]["StatsTotals"];
		};
		/**
		 * @description Sums of usage rows. A request counts once, on its model row, so the groups add up to the
		 *     total.
		 */
		StatsTotals: {
			/** @description Per category (the usage column names): tokens, calls, images, characters, seconds. */
			amounts: {
				[key: string]: number;
			};
			/**
			 * Format: int64
			 * @description Calculated cost, nano-USD. Rows without a price are not in it.
			 */
			cost_nano: number;
			/** @description Calculated cost ("API value") per category, nano-USD. */
			costs: {
				[key: string]: number;
			};
			/**
			 * Format: int64
			 * @description Requests with an error status.
			 */
			errors: number;
			/**
			 * Format: int64
			 * @description Rows whose cost is not complete (estimated usage or missing prices).
			 */
			incomplete: number;
			/**
			 * Format: int64
			 * @description The cost that providers reported (OpenRouter), nano-USD.
			 */
			reported_cost_nano: number;
			/** Format: int64 */
			requests: number;
			/**
			 * Format: int64
			 * @description Rows with usage but no price.
			 */
			unpriced: number;
		};
		Thinking: {
			adaptive: boolean;
			enabled: boolean;
		};
		/** @description USD per token. An empty field has no price. */
		TokenPrices: {
			/** Format: double */
			cache_write_1h?: number | null;
			/** Format: double */
			cache_write_5m?: number | null;
			/** Format: double */
			input_audio?: number | null;
			/** Format: double */
			input_audio_cached?: number | null;
			/** Format: double */
			input_image?: number | null;
			/** Format: double */
			input_image_cached?: number | null;
			/** Format: double */
			input_text?: number | null;
			/** Format: double */
			input_text_cached?: number | null;
			/** Format: double */
			output_audio?: number | null;
			/** Format: double */
			output_image?: number | null;
			/**
			 * Format: double
			 * @description Empty: the output text price.
			 */
			output_reasoning?: number | null;
			/** Format: double */
			output_text?: number | null;
		};
		TotpSetup: {
			otpauth_url: string;
			/** @description PNG image of the QR code, base64. */
			qr_png_base64: string;
			/** @description Base32 secret for manual entry. */
			secret: string;
		};
		UpdateAdmin: {
			disabled: boolean;
		};
		UsagePoll: {
			enabled: boolean;
			/**
			 * Format: int32
			 * @description Poll each account at this interval, 1 to 60 minutes. The poll is faster near the usage limit.
			 */
			minutes: number;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	register: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RegisterRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["FactorAdded"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	registration_options: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Options"];
				};
			};
		};
	};
	delete_passkey: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	change_password: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ChangePassword"];
			};
		};
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The current password is wrong or the new one is not valid */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	new_recovery_codes: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RecoveryCodes"];
				};
			};
			/** @description No second factor is active */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_factors: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Factors"];
				};
			};
		};
	};
	list_sessions: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionView"][];
				};
			};
		};
	};
	delete_session: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	start_totp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TotpSetup"];
				};
			};
			/** @description TOTP is already active */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	delete_totp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	confirm_totp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CodeRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["FactorAdded"];
				};
			};
			/** @description The code is wrong */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_admins: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"][];
				};
			};
		};
	};
	create_admin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateAdmin"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"];
				};
			};
			/** @description The username exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	delete_admin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description It would leave no enabled admin */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_admin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateAdmin"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description It would leave no enabled admin */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	reset_password: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ResetPassword"];
			};
		};
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	reset_factors: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_aliases: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AliasView"][];
				};
			};
		};
	};
	create_alias: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AliasSettings"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AliasView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_alias: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AliasSettings"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AliasView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	delete_alias: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_keys: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiKeyView"][];
				};
			};
		};
	};
	create_key: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["KeySettings"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CreatedKey"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_key: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["KeySettings"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiKeyView"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	revoke_key: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LoginResponse"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	passkey_login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AssertionRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	passkey_login_options: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Options"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	pending_methods: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Methods"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	verify_second_factor: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AssertionRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	second_factor_options: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Options"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	verify_recovery_code: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CodeRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	verify_totp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CodeRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_accounts: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AccountView"][];
				};
			};
		};
	};
	delete_account: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_account: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AccountUpdate"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AccountView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	sync_models: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AccountView"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description The account must be linked again */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description The model list sync failed */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	make_primary: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	refresh_now: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AccountView"];
				};
			};
			/** @description The refresh failed */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	refresh_usage: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AccountView"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description The account must be linked again, or its token must be refreshed */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description The ChatGPT backend limits the requests now */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description The usage poll failed */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	set_failover_order: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["FailoverOrder"];
			};
		};
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	start_device_link: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeviceLink"];
				};
			};
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	start_pkce_link: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PkceLink"];
				};
			};
		};
	};
	link_status: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				flow: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LinkStatus"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	cancel_link: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				flow: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	complete_pkce_link: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				flow: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PastedCallback"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LinkStatus"];
				};
			};
		};
	};
	list_connections: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectionView"][];
				};
			};
		};
	};
	create_connection: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["NewConnection"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectionView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	delete_connection: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_connection: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ConnectionUpdate"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectionView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	sync_connection: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectionView"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_models: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ModelView"][];
				};
			};
		};
	};
	update_model: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ModelUpdate"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ModelView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	model_prices: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ModelPrice"][];
				};
			};
		};
	};
	list_overrides: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["OverrideView"][];
				};
			};
		};
	};
	create_override: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["OverrideSettings"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["OverrideView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_override: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["OverridePrices"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["OverrideView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	delete_override: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	recompute_status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RecomputeStatus"];
				};
			};
		};
	};
	start_recompute: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RecomputeRequest"];
			};
		};
		responses: {
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RecomputeStatus"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_sources: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PriceSource"][];
				};
			};
		};
	};
	sync_now: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PriceSource"][];
				};
			};
		};
	};
	get_settings: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Settings"];
				};
			};
		};
	};
	put_settings: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Settings"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Settings"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	cron_preview: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CronPreviewRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CronPreview"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	setup_status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SetupStatus"];
				};
			};
		};
	};
	setup: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SetupRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			/** @description Setup is closed or the token is wrong */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	stats: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["StatsRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["StatsResponse"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
}
