/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/account/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Changes the own password and ends all other own sessions. */
		post: operations["change_password"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/sessions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_sessions"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/sessions/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete_session"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/admins": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_admins"];
		put?: never;
		post: operations["create_admin"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/admins/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete_admin"];
		options?: never;
		head?: never;
		/** Disables or enables an admin. Disabling ends all sessions of that admin. */
		patch: operations["update_admin"];
		trace?: never;
	};
	"/admins/{id}/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sets a new password and ends the sessions of that admin (for the own account: all other sessions). */
		post: operations["reset_password"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["logout"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["me"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/setup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["setup_status"];
		put?: never;
		/** Creates the first admin with the setup token and logs in. */
		post: operations["setup"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AdminView: {
			/** Format: int64 */
			created_at: number;
			disabled: boolean;
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			last_login_at?: number | null;
			username: string;
		};
		ChangePassword: {
			current_password: string;
			new_password: string;
		};
		CreateAdmin: {
			password: string;
			username: string;
		};
		ErrorBody: {
			error: components["schemas"]["ErrorDetail"];
		};
		ErrorDetail: {
			code: string;
			message: string;
		};
		LoginRequest: {
			password: string;
			username: string;
		};
		Me: {
			/** Format: int64 */
			id: number;
			username: string;
		};
		ResetPassword: {
			password: string;
		};
		SessionView: {
			/** Format: int64 */
			created_at: number;
			/** @description True for the session of this request. */
			current: boolean;
			/** Format: int64 */
			expires_at: number;
			/** Format: int64 */
			id: number;
			ip?: string | null;
			/** Format: int64 */
			last_seen_at: number;
			user_agent?: string | null;
		};
		SetupRequest: {
			password: string;
			token: string;
			username: string;
		};
		SetupStatus: {
			/** @description True when no admin exists yet. */
			required: boolean;
		};
		UpdateAdmin: {
			disabled: boolean;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	change_password: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ChangePassword"];
			};
		};
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The current password is wrong or the new one is not valid */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_sessions: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionView"][];
				};
			};
		};
	};
	delete_session: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_admins: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"][];
				};
			};
		};
	};
	create_admin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateAdmin"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"];
				};
			};
			/** @description The username exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	delete_admin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description It would leave no enabled admin */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_admin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateAdmin"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description It would leave no enabled admin */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	reset_password: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ResetPassword"];
			};
		};
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	setup_status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SetupStatus"];
				};
			};
		};
	};
	setup: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SetupRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			/** @description Setup is closed or the token is wrong */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
}
