/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/account/passkeys": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["register"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/passkeys/options": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["registration_options"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/passkeys/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete_passkey"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Changes the own password and ends all other own sessions. */
		post: operations["change_password"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/recovery-codes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Replaces the recovery codes. The old codes stop working. */
		post: operations["new_recovery_codes"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/second-factors": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_factors"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/sessions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_sessions"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/sessions/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete_session"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/totp": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Starts TOTP setup with a new secret. The secret is active only after confirmation. */
		post: operations["start_totp"];
		delete: operations["delete_totp"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/account/totp/confirm": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["confirm_totp"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/admins": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_admins"];
		put?: never;
		post: operations["create_admin"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/admins/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["delete_admin"];
		options?: never;
		head?: never;
		/** Disables or enables an admin. Disabling ends all sessions of that admin. */
		patch: operations["update_admin"];
		trace?: never;
	};
	"/admins/{id}/password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Sets a new password and ends the sessions of that admin (for the own account: all other sessions). */
		post: operations["reset_password"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/admins/{id}/second-factors/reset": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Removes all second factors of an admin and ends the sessions of that admin. */
		post: operations["reset_factors"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api-keys": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_keys"];
		put?: never;
		post: operations["create_key"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api-keys/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["update_key"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api-keys/{id}/revoke": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Revokes a key. It stops working at once. Revoked keys stay listed for the usage history. */
		post: operations["revoke_key"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["logout"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["me"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/passkey": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["passkey_login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/passkey/options": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["passkey_login_options"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** The second factors for the pending login. */
		get: operations["pending_methods"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor/passkey": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["verify_second_factor"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor/passkey/options": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["second_factor_options"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor/recovery-code": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["verify_recovery_code"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/second-factor/totp": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["verify_totp"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/accounts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["list_accounts"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/accounts/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Removes the account. If it was the primary account, the next one in the order becomes primary. */
		delete: operations["delete_account"];
		options?: never;
		head?: never;
		patch: operations["update_account"];
		trace?: never;
	};
	"/chatgpt/accounts/{id}/primary": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["make_primary"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/accounts/{id}/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["refresh_now"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/failover-order": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["set_failover_order"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/link/device": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["start_device_link"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/link/pkce": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["start_pkce_link"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/link/{flow}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["link_status"];
		put?: never;
		post?: never;
		delete: operations["cancel_link"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/chatgpt/link/{flow}/callback": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["complete_pkce_link"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/settings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["get_settings"];
		put: operations["put_settings"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/settings/cron-preview": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * The next 3 run times of a cron plan. The server computes them, so the dashboard shows what
		 *     the scheduler does.
		 */
		post: operations["cron_preview"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/setup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["setup_status"];
		put?: never;
		/** Creates the first admin with the setup token and logs in. */
		post: operations["setup"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AccountUpdate: {
			/** @description Take part in failover. */
			failover_enabled: boolean;
			label?: string | null;
			/** @description Needed when `refresh_mode` is `custom`. */
			refresh_cron?: string | null;
			/** @description `inherit`, `custom` or `disabled`. */
			refresh_mode: string;
		};
		AccountView: {
			/** Format: int64 */
			access_expires_at?: number | null;
			/** Format: int64 */
			created_at: number;
			email?: string | null;
			failover_enabled: boolean;
			/** Format: int64 */
			failover_order: number;
			/** Format: int64 */
			id: number;
			is_primary: boolean;
			label?: string | null;
			/** Format: int64 */
			last_refresh_at: number;
			last_refresh_error?: string | null;
			/** Format: int64 */
			last_refresh_failed_at?: number | null;
			/**
			 * Format: int64
			 * @description A usage-limit error blocks the account until this time.
			 */
			limited_until?: number | null;
			/** Format: int64 */
			models: number;
			/**
			 * Format: int64
			 * @description Next scheduled refresh, computed from the plan.
			 */
			next_refresh_at?: number | null;
			plan_type?: string | null;
			/** Format: int64 */
			primary_reset_at?: number | null;
			/**
			 * Format: double
			 * @description Usage limits from the last backend answer (usually a 5-hour and a weekly window).
			 */
			primary_used_percent?: number | null;
			/** Format: int64 */
			primary_window_minutes?: number | null;
			/** Format: int64 */
			quota_updated_at?: number | null;
			refresh_cron?: string | null;
			/** @description `inherit`, `custom` or `disabled`. */
			refresh_mode: string;
			/** Format: int64 */
			secondary_reset_at?: number | null;
			/** Format: double */
			secondary_used_percent?: number | null;
			/** Format: int64 */
			secondary_window_minutes?: number | null;
			/** @description `active` or `needs_relogin`. */
			status: string;
		};
		AdminView: {
			/** Format: int64 */
			created_at: number;
			disabled: boolean;
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			last_login_at?: number | null;
			/** @description True when the admin has TOTP or a passkey. */
			second_factor: boolean;
			username: string;
		};
		ApiKeyView: {
			allowlist: string[];
			/**
			 * Format: int64
			 * @description Parallel requests. `None`: the default of 8.
			 */
			concurrency_limit?: number | null;
			/** Format: int64 */
			created_at: number;
			created_by?: string | null;
			/** Format: int64 */
			expires_at?: number | null;
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			last_used_at?: number | null;
			name: string;
			prefix: string;
			/** Format: int64 */
			revoked_at?: number | null;
			/** Format: int64 */
			rpm_limit?: number | null;
			/** Format: int64 */
			tpm_limit?: number | null;
		};
		AssertionRequest: {
			ceremony: string;
			credential: unknown;
		};
		ChangePassword: {
			current_password: string;
			new_password: string;
		};
		CodeRequest: {
			code: string;
		};
		CreateAdmin: {
			password: string;
			username: string;
		};
		CreatedKey: {
			api_key: components["schemas"]["ApiKeyView"];
			/** @description The full key. It is shown only once. */
			key: string;
		};
		CronPreview: {
			/** @description The next 3 runs, unix seconds. */
			next_runs: number[];
		};
		CronPreviewRequest: {
			cron: string;
			/** @description Default: the instance time zone. */
			time_zone?: string | null;
		};
		DeviceLink: {
			flow: string;
			user_code: string;
			verification_url: string;
		};
		ErrorBody: {
			error: components["schemas"]["ErrorDetail"];
		};
		ErrorDetail: {
			code: string;
			message: string;
		};
		FactorAdded: {
			/** @description New recovery codes, only when this is the first second factor. Show them once. */
			recovery_codes?: string[] | null;
		};
		Factors: {
			passkeys: components["schemas"]["PasskeyView"][];
			/** Format: int64 */
			recovery_codes_left: number;
			totp: boolean;
		};
		Failover: {
			enabled: boolean;
			/**
			 * Format: int32
			 * @description Switch to the next account when its 5-hour or weekly usage reaches this percentage.
			 */
			threshold_percent: number;
		};
		FailoverOrder: {
			/** @description All account ids in the new order. */
			account_ids: number[];
		};
		/** @description Settings of a key. The same body is used to create and to change a key. */
		KeySettings: {
			/** @description Model patterns, for example `chatgpt/*` or `anthropic-main/claude-opus-5-5`. Empty: all models. */
			allowlist: string[];
			/** Format: int64 */
			concurrency_limit?: number | null;
			/** Format: int64 */
			expires_at?: number | null;
			name: string;
			/** Format: int64 */
			rpm_limit?: number | null;
			/** Format: int64 */
			tpm_limit?: number | null;
		};
		LinkStatus: {
			/** Format: int64 */
			account_id?: number | null;
			message?: string | null;
			/** @description `pending`, `done` or `failed`. */
			status: string;
		};
		LoginRequest: {
			password: string;
			username: string;
		};
		/** @description Either the logged-in admin, or the second factors to use next. */
		LoginResponse: {
			me?: components["schemas"]["Me"] | null;
			second_factor?: components["schemas"]["Methods"] | null;
		};
		Me: {
			/** Format: int64 */
			id: number;
			username: string;
		};
		/** @description The second factors an admin can use. */
		Methods: {
			passkey: boolean;
			recovery_code: boolean;
			totp: boolean;
		};
		/** @description WebAuthn options and credentials are passed through as JSON objects. */
		Options: {
			/** @description Id of this ceremony, to send back with the answer. */
			ceremony: string;
			/** @description Options for `navigator.credentials` (`publicKey` member). */
			options: unknown;
		};
		PasskeyView: {
			/** Format: int64 */
			created_at: number;
			/** Format: int64 */
			id: number;
			/** Format: int64 */
			last_used_at?: number | null;
			name: string;
		};
		PastedCallback: {
			url: string;
		};
		PkceLink: {
			/** @description Open this address, log in, then paste the address of the page you land on. */
			authorize_url: string;
			flow: string;
		};
		RecoveryCodes: {
			recovery_codes: string[];
		};
		/** @description Scheduled token refresh of the ChatGPT accounts. */
		RefreshSchedule: {
			/** @description 5-field cron: minute hour day-of-month month day-of-week. */
			cron: string;
			enabled: boolean;
		};
		RegisterRequest: {
			ceremony: string;
			credential: unknown;
			name: string;
		};
		ResetPassword: {
			password: string;
		};
		SessionView: {
			/** Format: int64 */
			created_at: number;
			/** @description True for the session of this request. */
			current: boolean;
			/** Format: int64 */
			expires_at: number;
			/** Format: int64 */
			id: number;
			ip?: string | null;
			/** Format: int64 */
			last_seen_at: number;
			user_agent?: string | null;
		};
		Settings: {
			failover: components["schemas"]["Failover"];
			refresh: components["schemas"]["RefreshSchedule"];
			/** @description IANA time zone, for example `Europe/Berlin`. Cron plans use it. */
			time_zone: string;
		};
		SetupRequest: {
			password: string;
			token: string;
			username: string;
		};
		SetupStatus: {
			/** @description True when no admin exists yet. */
			required: boolean;
		};
		TotpSetup: {
			otpauth_url: string;
			/** @description PNG image of the QR code, base64. */
			qr_png_base64: string;
			/** @description Base32 secret for manual entry. */
			secret: string;
		};
		UpdateAdmin: {
			disabled: boolean;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	register: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RegisterRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["FactorAdded"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	registration_options: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Options"];
				};
			};
		};
	};
	delete_passkey: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	change_password: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ChangePassword"];
			};
		};
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The current password is wrong or the new one is not valid */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	new_recovery_codes: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RecoveryCodes"];
				};
			};
			/** @description No second factor is active */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_factors: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Factors"];
				};
			};
		};
	};
	list_sessions: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionView"][];
				};
			};
		};
	};
	delete_session: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	start_totp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TotpSetup"];
				};
			};
			/** @description TOTP is already active */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	delete_totp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	confirm_totp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CodeRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["FactorAdded"];
				};
			};
			/** @description The code is wrong */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_admins: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"][];
				};
			};
		};
	};
	create_admin: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateAdmin"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"];
				};
			};
			/** @description The username exists */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	delete_admin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description It would leave no enabled admin */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_admin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateAdmin"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminView"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			/** @description It would leave no enabled admin */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	reset_password: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ResetPassword"];
			};
		};
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	reset_factors: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_keys: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiKeyView"][];
				};
			};
		};
	};
	create_key: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["KeySettings"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CreatedKey"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_key: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["KeySettings"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiKeyView"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	revoke_key: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LoginResponse"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	passkey_login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AssertionRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	passkey_login_options: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Options"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	pending_methods: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Methods"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	verify_second_factor: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AssertionRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	second_factor_options: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Options"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	verify_recovery_code: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CodeRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	verify_totp: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CodeRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	list_accounts: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AccountView"][];
				};
			};
		};
	};
	delete_account: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	update_account: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AccountUpdate"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AccountView"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	make_primary: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	refresh_now: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AccountView"];
				};
			};
			/** @description The refresh failed */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	set_failover_order: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["FailoverOrder"];
			};
		};
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	start_device_link: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeviceLink"];
				};
			};
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	start_pkce_link: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PkceLink"];
				};
			};
		};
	};
	link_status: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				flow: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LinkStatus"];
				};
			};
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	cancel_link: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				flow: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	complete_pkce_link: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				flow: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PastedCallback"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LinkStatus"];
				};
			};
		};
	};
	get_settings: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Settings"];
				};
			};
		};
	};
	put_settings: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Settings"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Settings"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	cron_preview: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CronPreviewRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CronPreview"];
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
	setup_status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SetupStatus"];
				};
			};
		};
	};
	setup: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SetupRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Me"];
				};
			};
			/** @description Setup is closed or the token is wrong */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorBody"];
				};
			};
		};
	};
}
