/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminsRouteImport } from './routes/_app/admins'
import { Route as AppAliasesRouteImport } from './routes/_app/aliases'
import { Route as AppApiKeysRouteImport } from './routes/_app/api-keys'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppPricingRouteImport } from './routes/_app/pricing'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions'
import { Route as AppUsageRouteImport } from './routes/_app/usage'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminsRoute = AppAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppRoute,
} as any)
const AppAliasesRoute = AppAliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admins': typeof AppAdminsRoute
  '/aliases': typeof AppAliasesRoute
  '/api-keys': typeof AppApiKeysRoute
  '/connections': typeof AppConnectionsRoute
  '/pricing': typeof AppPricingRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/usage': typeof AppUsageRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admins': typeof AppAdminsRoute
  '/aliases': typeof AppAliasesRoute
  '/api-keys': typeof AppApiKeysRoute
  '/connections': typeof AppConnectionsRoute
  '/pricing': typeof AppPricingRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/usage': typeof AppUsageRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/admins': typeof AppAdminsRoute
  '/_app/aliases': typeof AppAliasesRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/admins'
    | '/aliases'
    | '/api-keys'
    | '/connections'
    | '/pricing'
    | '/security'
    | '/settings'
    | '/subscriptions'
    | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/admins'
    | '/aliases'
    | '/api-keys'
    | '/connections'
    | '/pricing'
    | '/security'
    | '/settings'
    | '/subscriptions'
    | '/usage'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/admins'
    | '/_app/aliases'
    | '/_app/api-keys'
    | '/_app/connections'
    | '/_app/pricing'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/subscriptions'
    | '/_app/usage'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admins': {
      id: '/_app/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AppAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aliases': {
      id: '/_app/aliases'
      path: '/aliases'
      fullPath: '/aliases'
      preLoaderRoute: typeof AppAliasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminsRoute: typeof AppAdminsRoute
  AppAliasesRoute: typeof AppAliasesRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppPricingRoute: typeof AppPricingRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminsRoute: AppAdminsRoute,
  AppAliasesRoute: AppAliasesRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppPricingRoute: AppPricingRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
